Data Concatenation

In [1]:
import pandas as pd

In [5]:
# Concatenation
df1 = pd.DataFrame({
    "id": [1, 2, 3],
    "name": ["Adam", "Bob", "Charlie"]
})

df2 = pd.DataFrame({
    "id": [4, 5, 6],
    "name": ["David", "Eva", "Frank"]
})


pd.concat([df1, df2], ignore_index=True)    # Row wise concatenation - new index

   id     name
0   1     Adam
1   2      Bob
2   3  Charlie
3   4    David
4   5      Eva
5   6    Frank

In [6]:
pd.concat([df1, df2])                       # Row wise concatenation

   id     name
0   1     Adam
1   2      Bob
2   3  Charlie
0   4    David
1   5      Eva
2   6    Frank

In [7]:
pd.concat([df1, df2], axis=1)               # Col wise concatenation

   id     name  id   name
0   1     Adam   4  David
1   2      Bob   5    Eva
2   3  Charlie   6  Frank